<?php

/**
 * BaseOcupacion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nombre
 * @property Doctrine_Collection $Adulto
 * 
 * @method string              getNombre() Returns the current record's "nombre" value
 * @method Doctrine_Collection getAdulto() Returns the current record's "Adulto" collection
 * @method Ocupacion           setNombre() Sets the current record's "nombre" value
 * @method Ocupacion           setAdulto() Sets the current record's "Adulto" collection
 * 
 * @package    inasscentros
 * @subpackage model
 * @author     Alexis Limongi
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOcupacion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ocupacion');
        $this->hasColumn('nombre', 'string', 120, array(
             'type' => 'string',
             'notnull' => true,
             'notblank' => true,
             'minlength' => 4,
             'length' => 120,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Adulto', array(
             'local' => 'id',
             'foreign' => 'ocupacion_id'));
    }
}