<?php

/**
 * BaseConsejocomunal
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $codigo
 * @property string $nombre
 * @property integer $estado_id
 * @property integer $municipio_id
 * @property integer $parroquia_id
 * @property string $sector
 * @property boolean $activo
 * @property string $contacto
 * @property string $telefono
 * @property Estado $Estado
 * @property Municipio $Municipio
 * @property Parroquia $Parroquia
 * @property Doctrine_Collection $Comite
 * 
 * @method integer             getId()           Returns the current record's "id" value
 * @method string              getCodigo()       Returns the current record's "codigo" value
 * @method string              getNombre()       Returns the current record's "nombre" value
 * @method integer             getEstadoId()     Returns the current record's "estado_id" value
 * @method integer             getMunicipioId()  Returns the current record's "municipio_id" value
 * @method integer             getParroquiaId()  Returns the current record's "parroquia_id" value
 * @method string              getSector()       Returns the current record's "sector" value
 * @method boolean             getActivo()       Returns the current record's "activo" value
 * @method string              getContacto()     Returns the current record's "contacto" value
 * @method string              getTelefono()     Returns the current record's "telefono" value
 * @method Estado              getEstado()       Returns the current record's "Estado" value
 * @method Municipio           getMunicipio()    Returns the current record's "Municipio" value
 * @method Parroquia           getParroquia()    Returns the current record's "Parroquia" value
 * @method Doctrine_Collection getComite()       Returns the current record's "Comite" collection
 * @method Consejocomunal      setId()           Sets the current record's "id" value
 * @method Consejocomunal      setCodigo()       Sets the current record's "codigo" value
 * @method Consejocomunal      setNombre()       Sets the current record's "nombre" value
 * @method Consejocomunal      setEstadoId()     Sets the current record's "estado_id" value
 * @method Consejocomunal      setMunicipioId()  Sets the current record's "municipio_id" value
 * @method Consejocomunal      setParroquiaId()  Sets the current record's "parroquia_id" value
 * @method Consejocomunal      setSector()       Sets the current record's "sector" value
 * @method Consejocomunal      setActivo()       Sets the current record's "activo" value
 * @method Consejocomunal      setContacto()     Sets the current record's "contacto" value
 * @method Consejocomunal      setTelefono()     Sets the current record's "telefono" value
 * @method Consejocomunal      setEstado()       Sets the current record's "Estado" value
 * @method Consejocomunal      setMunicipio()    Sets the current record's "Municipio" value
 * @method Consejocomunal      setParroquia()    Sets the current record's "Parroquia" value
 * @method Consejocomunal      setComite()       Sets the current record's "Comite" collection
 * 
 * @package    inasscomite
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseConsejocomunal extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('consejocomunal');
        $this->hasColumn('id', 'integer', 4, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('codigo', 'string', 30, array(
             'type' => 'string',
             'unique' => true,
             'notnull' => true,
             'notblank' => true,
             'length' => 30,
             ));
        $this->hasColumn('nombre', 'string', 120, array(
             'type' => 'string',
             'notnull' => true,
             'notblank' => true,
             'minlength' => 4,
             'length' => 120,
             ));
        $this->hasColumn('estado_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('municipio_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('parroquia_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('sector', 'string', 80, array(
             'type' => 'string',
             'notnull' => false,
             'notblank' => false,
             'minlength' => 4,
             'length' => 80,
             ));
        $this->hasColumn('activo', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('contacto', 'string', 120, array(
             'type' => 'string',
             'notnull' => true,
             'notblank' => true,
             'minlength' => 4,
             'length' => 120,
             ));
        $this->hasColumn('telefono', 'string', 30, array(
             'type' => 'string',
             'notnull' => true,
             'notblank' => true,
             'minlength' => 11,
             'length' => 30,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Estado', array(
             'local' => 'estado_id',
             'foreign' => 'id'));

        $this->hasOne('Municipio', array(
             'local' => 'municipio_id',
             'foreign' => 'id'));

        $this->hasOne('Parroquia', array(
             'local' => 'parroquia_id',
             'foreign' => 'id'));

        $this->hasMany('Comite', array(
             'local' => 'id',
             'foreign' => 'consejo_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
    }
}