<?php

/**
 * BaseEstado
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nombre
 * @property Doctrine_Collection $User
 * @property Doctrine_Collection $Municipio
 * @property Doctrine_Collection $Consejocomunal
 * @property Doctrine_Collection $Comite
 * @property Doctrine_Collection $Adulto
 * 
 * @method integer             getId()             Returns the current record's "id" value
 * @method string              getNombre()         Returns the current record's "nombre" value
 * @method Doctrine_Collection getUser()           Returns the current record's "User" collection
 * @method Doctrine_Collection getMunicipio()      Returns the current record's "Municipio" collection
 * @method Doctrine_Collection getConsejocomunal() Returns the current record's "Consejocomunal" collection
 * @method Doctrine_Collection getComite()         Returns the current record's "Comite" collection
 * @method Doctrine_Collection getAdulto()         Returns the current record's "Adulto" collection
 * @method Estado              setId()             Sets the current record's "id" value
 * @method Estado              setNombre()         Sets the current record's "nombre" value
 * @method Estado              setUser()           Sets the current record's "User" collection
 * @method Estado              setMunicipio()      Sets the current record's "Municipio" collection
 * @method Estado              setConsejocomunal() Sets the current record's "Consejocomunal" collection
 * @method Estado              setComite()         Sets the current record's "Comite" collection
 * @method Estado              setAdulto()         Sets the current record's "Adulto" collection
 * 
 * @package    inasscomite
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEstado extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('estado');
        $this->hasColumn('id', 'integer', 4, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 120, array(
             'type' => 'string',
             'notnull' => true,
             'notblank' => true,
             'minlength' => 4,
             'length' => 120,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('sfGuardUser as User', array(
             'refClass' => 'UserEstado',
             'local' => 'estado_id',
             'foreign' => 'user_id'));

        $this->hasMany('Municipio', array(
             'local' => 'id',
             'foreign' => 'estado_id'));

        $this->hasMany('Consejocomunal', array(
             'local' => 'id',
             'foreign' => 'estado_id'));

        $this->hasMany('Comite', array(
             'local' => 'id',
             'foreign' => 'estado_id'));

        $this->hasMany('Adulto', array(
             'local' => 'id',
             'foreign' => 'estado_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
    }
}