all:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql:host=localhost;dbname=inasscomite;unix_socket=/var/run/mysqld/mysqld.sock'
      username: inasscomite
      password: '1Nn@s5C0wi7#'
#      username: root
#      password: 'lennyn'
